### ISSUE TITLE
table readme is horizontal scale, vertical make it better  

### ISSUE THREAD

**Issue by chandru1003** [jlooper/blog#46]
readme file in blog->section->article in horizontal scale
need to scroll long to check the content, the vertical scale will be better

**Comment by jlooper** [comment]
This is displayed here: https://www.jenlooper.com/sections/articles/ - are you viewing it at that site?

**Comment by chandru1003** [comment]
NO actually, I don't know about that, can I know how you did that ?
btw blog looking nice
